USE Bookstore_DB;

--  회원(MEMBER) 테이블 생성 
CREATE TABLE MEMBER (
    member_id VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
